spring:
  application:
    name: schoolar
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${OAUTH_ISSUER_URI:https://ctream.eu.auth0.com/}
          jwk-set-uri: https://ctream.eu.auth0.com/.well-known/jwks.json
